{"uuid": "3974ecbd-c129-4d15-ad01-ca4560c00904", "children": ["93cdaad5-596c-49a3-82cb-8c1ffd3c0f77", "77e5370f-881b-4968-951e-6f00eb79578e", "e312ca21-653d-4dbb-825a-20a4fac14f05", "33ae7a1b-6eca-4d61-84d5-4d9c0ce0c50c", "eebdcdf4-9908-441f-ade1-2f4707c7fcb8", "018ffc4f-7e3c-4a90-a1f3-e72350a1f7b1"], "befores": [{"name": "获取用户token", "status": "broken", "statusDetails": {"message": "requests.exceptions.ProxyError: HTTPSConnectionPool(host='hapi.6noblexc.com', port=443): Max retries exceeded with url: /api/6nobleapi/ucenter/login (Caused by ProxyError('Your proxy appears to only use HTTP and not HTTPS, try changing your proxy URL to be HTTP. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#https-proxy-error-http-proxy', SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1123)'))))\n", "trace": "  File \"C:\\Users\\jay52\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\jay52\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\jay52\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 890, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\jay52\\PycharmProjects\\6noble\\conftest.py\", line 62, in Api_Token\n    res=ak.post(url=url,data=data)\n  File \"C:\\Users\\jay52\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\allure_commons\\_allure.py\", line 172, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\jay52\\PycharmProjects\\6noble\\KeyWords\\Api_Keys.py\", line 13, in post\n    return requests.post(url=url,data=data,**kwargs)\n  File \"C:\\Users\\jay52\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\api.py\", line 115, in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n  File \"C:\\Users\\jay52\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"C:\\Users\\jay52\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py\", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"C:\\Users\\jay52\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py\", line 701, in send\n    r = adapter.send(request, **kwargs)\n  File \"C:\\Users\\jay52\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py\", line 559, in send\n    raise ProxyError(e, request=request)\n"}, "steps": [{"name": "发送登录接口请求，并生成用户的token，整个项目仅生成一次", "status": "broken", "statusDetails": {"message": "requests.exceptions.ProxyError: HTTPSConnectionPool(host='hapi.6noblexc.com', port=443): Max retries exceeded with url: /api/6nobleapi/ucenter/login (Caused by ProxyError('Your proxy appears to only use HTTP and not HTTPS, try changing your proxy URL to be HTTP. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#https-proxy-error-http-proxy', SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1123)'))))\n", "trace": "  File \"C:\\Users\\jay52\\PycharmProjects\\6noble\\conftest.py\", line 62, in Api_Token\n    res=ak.post(url=url,data=data)\n  File \"C:\\Users\\jay52\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\allure_commons\\_allure.py\", line 172, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\jay52\\PycharmProjects\\6noble\\KeyWords\\Api_Keys.py\", line 13, in post\n    return requests.post(url=url,data=data,**kwargs)\n  File \"C:\\Users\\jay52\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\api.py\", line 115, in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n  File \"C:\\Users\\jay52\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"C:\\Users\\jay52\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py\", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"C:\\Users\\jay52\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py\", line 701, in send\n    r = adapter.send(request, **kwargs)\n  File \"C:\\Users\\jay52\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py\", line 559, in send\n    raise ProxyError(e, request=request)\n"}, "steps": [{"name": "发送post请求", "status": "broken", "statusDetails": {"message": "requests.exceptions.ProxyError: HTTPSConnectionPool(host='hapi.6noblexc.com', port=443): Max retries exceeded with url: /api/6nobleapi/ucenter/login (Caused by ProxyError('Your proxy appears to only use HTTP and not HTTPS, try changing your proxy URL to be HTTP. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#https-proxy-error-http-proxy', SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1123)'))))\n", "trace": "  File \"C:\\Users\\jay52\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\allure_commons\\_allure.py\", line 172, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\jay52\\PycharmProjects\\6noble\\KeyWords\\Api_Keys.py\", line 13, in post\n    return requests.post(url=url,data=data,**kwargs)\n  File \"C:\\Users\\jay52\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\api.py\", line 115, in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n  File \"C:\\Users\\jay52\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"C:\\Users\\jay52\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py\", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"C:\\Users\\jay52\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py\", line 701, in send\n    r = adapter.send(request, **kwargs)\n  File \"C:\\Users\\jay52\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py\", line 559, in send\n    raise ProxyError(e, request=request)\n"}, "parameters": [{"name": "url", "value": "'https://hapi.6noblexc.com/api/6nobleapi/ucenter/login'"}, {"name": "data", "value": "{'account': '15130828', 'password': 'e10adc3949ba59abbe56e057f20f883e', 'publicKey': 'pvj9bTwwaY4YdPiwRBH5RE25o9ZM8BHG'}"}], "start": 1659323568214, "stop": 1659323628258}], "start": 1659323568214, "stop": 1659323628267}], "start": 1659323568214, "stop": 1659323628268}], "start": 1659323568214, "stop": 1659323629162}