{"uuid": "0705002a-95cb-4496-9295-627a421bfce9", "children": ["34c9cdd8-322b-44fd-8dce-3b05987bef2d", "a0fc9289-4677-460b-993b-7e12725f7ac3", "48e7433a-b269-42ca-861f-c50755e30fb1", "7644ae4d-6727-4000-b3f3-713518a34347", "188b8b1f-3d54-4904-98b3-68cf29561760", "99ca6cd0-10f3-497b-bf63-3d149dfc72dd"], "befores": [{"name": "获取用户token", "status": "broken", "statusDetails": {"message": "requests.exceptions.ProxyError: HTTPSConnectionPool(host='hapi.6noblexc.com', port=443): Max retries exceeded with url: /api/6nobleapi/ucenter/login (Caused by ProxyError('Your proxy appears to only use HTTP and not HTTPS, try changing your proxy URL to be HTTP. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#https-proxy-error-http-proxy', SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1123)'))))\n", "trace": "  File \"C:\\Users\\jay52\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\jay52\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\jay52\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 890, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\jay52\\PycharmProjects\\6noble\\conftest.py\", line 62, in Api_Token\n    res=ak.post(url=url,data=data)\n  File \"C:\\Users\\jay52\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\allure_commons\\_allure.py\", line 172, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\jay52\\PycharmProjects\\6noble\\KeyWords\\Api_Keys.py\", line 13, in post\n    return requests.post(url=url,data=data,**kwargs)\n  File \"C:\\Users\\jay52\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\api.py\", line 115, in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n  File \"C:\\Users\\jay52\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"C:\\Users\\jay52\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py\", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"C:\\Users\\jay52\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py\", line 701, in send\n    r = adapter.send(request, **kwargs)\n  File \"C:\\Users\\jay52\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py\", line 559, in send\n    raise ProxyError(e, request=request)\n"}, "steps": [{"name": "发送登录接口请求，并生成用户的token，整个项目仅生成一次", "status": "broken", "statusDetails": {"message": "requests.exceptions.ProxyError: HTTPSConnectionPool(host='hapi.6noblexc.com', port=443): Max retries exceeded with url: /api/6nobleapi/ucenter/login (Caused by ProxyError('Your proxy appears to only use HTTP and not HTTPS, try changing your proxy URL to be HTTP. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#https-proxy-error-http-proxy', SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1123)'))))\n", "trace": "  File \"C:\\Users\\jay52\\PycharmProjects\\6noble\\conftest.py\", line 62, in Api_Token\n    res=ak.post(url=url,data=data)\n  File \"C:\\Users\\jay52\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\allure_commons\\_allure.py\", line 172, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\jay52\\PycharmProjects\\6noble\\KeyWords\\Api_Keys.py\", line 13, in post\n    return requests.post(url=url,data=data,**kwargs)\n  File \"C:\\Users\\jay52\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\api.py\", line 115, in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n  File \"C:\\Users\\jay52\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"C:\\Users\\jay52\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py\", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"C:\\Users\\jay52\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py\", line 701, in send\n    r = adapter.send(request, **kwargs)\n  File \"C:\\Users\\jay52\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py\", line 559, in send\n    raise ProxyError(e, request=request)\n"}, "steps": [{"name": "发送post请求", "status": "broken", "statusDetails": {"message": "requests.exceptions.ProxyError: HTTPSConnectionPool(host='hapi.6noblexc.com', port=443): Max retries exceeded with url: /api/6nobleapi/ucenter/login (Caused by ProxyError('Your proxy appears to only use HTTP and not HTTPS, try changing your proxy URL to be HTTP. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#https-proxy-error-http-proxy', SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1123)'))))\n", "trace": "  File \"C:\\Users\\jay52\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\allure_commons\\_allure.py\", line 172, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\jay52\\PycharmProjects\\6noble\\KeyWords\\Api_Keys.py\", line 13, in post\n    return requests.post(url=url,data=data,**kwargs)\n  File \"C:\\Users\\jay52\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\api.py\", line 115, in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n  File \"C:\\Users\\jay52\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"C:\\Users\\jay52\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py\", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"C:\\Users\\jay52\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py\", line 701, in send\n    r = adapter.send(request, **kwargs)\n  File \"C:\\Users\\jay52\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py\", line 559, in send\n    raise ProxyError(e, request=request)\n"}, "parameters": [{"name": "url", "value": "'https://hapi.6noblexc.com/api/6nobleapi/ucenter/login'"}, {"name": "data", "value": "{'account': '15130828', 'password': 'e10adc3949ba59abbe56e057f20f883e', 'publicKey': 'pvj9bTwwaY4YdPiwRBH5RE25o9ZM8BHG'}"}], "start": 1661338699149, "stop": 1661338759188}], "start": 1661338699149, "stop": 1661338759196}], "start": 1661338699148, "stop": 1661338759197}], "start": 1661338699148, "stop": 1661338759895}